### PR TITLE
I discovered my inner geek and am on my road to fame

### PR DESCRIPTION
**Pull request by MeloCodeHi**
thanks for the troubleshoot this morning lol its the little details...

### CODE REVIEW

**Review by hishayness — CHANGES_REQUESTED** [review]
Great job on the first commit! The only problem is, I think you unintentionally altered someone else's comment. Take a look at the 'diff' in the **Files changed** tab

https://github.com/codehanadev/web/pull/2/files

**Comment by MeloCodeHi** [comment]
how do i resubmit my edits?

**Review by codehanadev — APPROVED** [review]
Looks great!

**Review by codehanadev — DISMISSED** [review]
Looks great!

**Review by hishayness — APPROVED** [review]

**Pull request merged**
